# GitHub Actions Workflow for Continuous Integration and Continuous Delivery

name: CI

on:
  push:

permissions:
  contents: read
  statuses: write
  checks: write

jobs:
  super-linter:
    name: CI / Super-Linter
    uses: cordada/github-actions-utils/.github/workflows/super-linter.yaml@master
    with:
      default_git_branch: develop

      validate_editorconfig: true
      validate_markdown: true
