# GitHub Actions Workflow for Deployment

name: Deploy

on:
  workflow_call:
    inputs:
      artifacts_path:
        type: string
        required: true

permissions:
  contents: read

env:
  PYTHON_VIRTUALENV_ACTIVATE: .pyenv/bin/activate

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Check Out VCS Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.9"

      - name: Restoring/Saving Cache
        uses: actions/cache@v3
        with:
          path: ".pyenv"
          key: py-v1-deps-${{ runner.os }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}

      - name: Restore Artifacts (Release)
        uses: actions/download-artifact@v3
        with:
          name: release
          path: ${{ inputs.artifacts_path }}/

      - name: Deploy
        run: |
          source "$PYTHON_VIRTUALENV_ACTIVATE"
          make deploy \
            TWINE_USERNAME="${PYPI_USERNAME:?}" \
            TWINE_PASSWORD="${PYPI_PASSWORD:?}"
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          TWINE_NON_INTERACTIVE: "true"
