# GitHub Actions Workflow for Deployment

name: Deploy

on:
  workflow_call:
    inputs:
      deploy_env:
        type: string
        required: true
        description: Deployment Environment
      artifacts_path:
        type: string
        required: true

permissions:
  contents: read

env:
  PYTHON_VIRTUALENV_ACTIVATE: .pyenv/bin/activate

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    environment: ${{ inputs.deploy_env }}

    steps:
      - name: Check Out VCS Repository
        uses: actions/checkout@v3.5.3

      - name: Set Up Python
        id: set_up_python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.10.13"

      - name: Restoring/Saving Cache
        uses: actions/cache@v3.3.1
        with:
          path: ".pyenv"
          key: py-v1-deps-${{ runner.os }}-${{ steps.set_up_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}-${{ hashFiles('Makefile', 'make/**.mk') }}

      - name: Restore Artifacts (Release)
        uses: actions/download-artifact@v3.0.2
        with:
          name: release
          path: ${{ inputs.artifacts_path }}/

      - name: Deploy
        run: |
          source "$PYTHON_VIRTUALENV_ACTIVATE"
          make deploy \
            TWINE_USERNAME="${PYPI_USERNAME:?}" \
            TWINE_PASSWORD="${PYPI_PASSWORD:?}"
        env:
          PYPI_USERNAME: ${{ vars.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          TWINE_NON_INTERACTIVE: "true"
