# GitHub Actions Workflow for Release

name: Release

on:
  workflow_call:

permissions:
  contents: read

env:
  PYTHON_VIRTUALENV_ACTIVATE: .pyenv/bin/activate

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04

    env:
      ARTIFACTS_PATH: dist

    outputs:
      artifacts_path: ${{ env.ARTIFACTS_PATH }}

    steps:
      - name: Check Out VCS Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.9"

      - name: Create Python Virtual Environment
        run: make python-virtualenv PYTHON_VIRTUALENV_DIR=".pyenv"

      - name: Restoring/Saving Cache
        uses: actions/cache@v3
        with:
          path: ".pyenv"
          key: py-v1-deps-${{ runner.os }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}

      - name: Install Dependencies
        run: |
          source "$PYTHON_VIRTUALENV_ACTIVATE"
          make install-deps-dev

      - name: Build
        run: |
          source "$PYTHON_VIRTUALENV_ACTIVATE"
          make clean-build build

      - name: Build for Distribution
        run: |
          source "$PYTHON_VIRTUALENV_ACTIVATE"
          make dist

      - name: Store Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ${{ env.ARTIFACTS_PATH }}/
          if-no-files-found: error
          retention-days: 1
